### ISSUE TITLE
Arch installation error (preinstall.py is not valid for python3)

### ISSUE THREAD

**Issue by yglukhov** [LedgerHQ/lib-ledger-core-node-bindings#17] opened 2018-08-18 09:02 UTC
Installing `ledger-live` in arch linux eventually calls `python preinstall.py` of this repo, which fails if `python` is of version 3. Ideally `preinstall.py` should be python version agnostic.

**Comment by meriadec** [comment] 2018-08-27 14:04
The problem is even with python version agnostic preinstall script, the required python version will still be 2.7 because node-gyp need it (https://github.com/nodejs/node-gyp#on-unix).

**Comment by yglukhov** [comment] 2018-08-27 14:36
The issue is that the package can not be installed when `python` is a symlink to `python3`. This is more and more true as time goes. I didn't do it manually on my Arch, so I suppose that's the default.

**Comment by Vedrillan** [comment] 2019-01-29 20:34
Proposal made in PR #26 

I have yet to encounter a Linux distrib that hasn't already both /usr/bin/python2 and /usr/bin/python2 with /usr/bin/python being a symlink to one of them. So forcing python2 should just do the trick.

Gyp on itself is capable of invoking python2 if it is available on the current system, even if /usr/bin/python is actually pointing to python3.

**Comment by meriadec** [comment] 2019-04-17 13:26
closed by #26

**Closed by meriadec** 2019-04-17 13:26 UTC
